services:
  db:
    image: postgres:16.2-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:PG_PORT"

#if (includeAdminer == "true")
  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
    environment:
      ADMINER_DESIGN: dracula
#endif

#if (includeAspireDashboard == "true")
  dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard
    container_name: aspire-dashboard
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: false
    ports:
      - "18888:18888"
      - "4317:18889"
#endif    
volumes:
  db_data:
